# Generated by Django 4.1.7 on 2023-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_position_alter_modelemployee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelemployee',
            name='emp_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelemployee',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
